[buildPlans.Hylosevka]
family = "hylosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Hylosevka.variants.design]
capital-a = "straight-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "vertical-crossing"
capital-r = "straight-serifless"
capital-v = "straight-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "tailed"
g = "single-storey-earless-rounded"
i = "tailed-serifed"
j = "serifed"
k = "cursive-serifless"
l = "tailed-serifed"
m = "earless-corner-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
t = "bent-hook-asymmetric"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-vertical-sides-serifless"
x = "straight-serifless"
y = "cursive-serifless"
z = "straight-serifless"
eszet = "sulzbacher-descending-serifless"
lower-lambda = "straight-turn"
zero = "dotted"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "open"
five = "upright-flat"
six = "open-contour"
seven = "curly-serifless"
eight = "two-circles"
nine = "open-contour"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
caret = "high"
paren = "normal"
brace = "straight"
ampersand = "lower-open"
at = "compact"
dollar = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"

[buildPlans.Hylosevka.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.Hylosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"
